server:
  port: 8888
  servlet:
    context-path: /auth-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 123
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime: 36000000



integration:
  account-service:
    url: http://localhost:8189/account-service
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 500
